### ISSUE TITLE
Page tabs can also show current selection

### ISSUE THREAD

**Issue by swxk19** [AY2223S2-CS2103T-T15-4/tp#139]
<img width="48" alt="image" src="https://user-images.githubusercontent.com/45385178/228359144-5f42a3ee-6508-446e-ab70-34874a28d73d.png">

e.g under the "Groups" label, maybe can indicate the currently selected group also

**Comment by tyx021** [comment]
Actually this was already displayed on top, would it be better to keep left side bar clean?
![image](https://user-images.githubusercontent.com/97380048/228418551-8fa6813f-3012-451c-a7e7-3f69dc465f20.png)

**Comment by afiqzu** [comment]
Hmm @tyx021 I feel that we shouldn't remove the left bar as they act as page tabs to show clearly to the user what page they are on so that they can use the relevant commands, and the top bar (navigation bar) was to show exactly which course/group/session/task they are on. But @swxk19 yes as @tyx021 mentioned the current selected group is already shown in the navigation bar but maybe I can adjust the font to make it more noticeable? 🤔

**Comment by tyx021** [comment]
Ohh what I meant is keeping only “Groups” on left bar instead of 
“Group
T01”

**Comment by afiqzu** [comment]
Ahh icic

**Comment by swxk19** [comment]
ah, i didn't notice the indicator at the top. my bad
