### ISSUE TITLE
Fix remark command

### ISSUE THREAD

**Issue by tyx021** [AY2223S2-CS2103T-T15-4/tp#203]
#194 

Problem: We are treating input without r/ as the same type of input (e.g. `remark 1 loves to read` is treated same as `remark 1`)

Possibility: First check if prefix `r/` exists in the input, then check for above case.

**Comment by swxk19** [comment]
possibly can do away with dealing with prefixes at all, since there is only 1 field to edit, it is already implicitly implied that whatever argument will definitely be a remark. 
A possible cheap fix would be just to tokenise the command (already have a function for this) and read whatever tokens come at index > 1

**Comment by swxk19** [comment]
similar to how `edit course` works, no prefix needed since the only thing to edit is the name. Can copy how its implemented
